### ISSUE TITLE
License for weights

### ISSUE THREAD

**Issue by ieee8023** [mi2rl/CheSS#23]
Hello, what is the license for the weights? I would like to add them to the TorchXRayVision library https://github.com/mlmed/torchxrayvision if possible.

**Comment by kyungjincho** [comment]
We are currently planning to set the license to Apache 2.0, and adding to TorchXRayVision is welcome. 

However, it seems that the corresponding author needs to confirm it.
So could you please wait a moment?

Thanks again!

**Comment by kyungjincho** [comment]
Hi, @ieee8023. 
Our corresponding author confirmed. 
You can add freely.

**Comment by ieee8023** [comment]
Awesome thanks!
